import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

import { onRequest as handleMiddleware } from "./_middleware"; // _middlewareをインポート

export const onRequest = async (context) => {
    const { request, next } = context;

    // Middlewareを先に実行
    const middlewareResponse = await handleMiddleware(context);
    if (middlewareResponse) {
        return middlewareResponse;
    }

    // 次にRemixのハンドラーを実行
    const remixHandler = createPagesFunctionHandler({ build });
    return remixHandler(context);
};
